// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63D4XM6A-9_tqRW0YsBAh-XsLaEXGOIY',
    appId: '1:222477309527:web:577c9307b2643d721d3512',
    messagingSenderId: '222477309527',
    projectId: 'renrakucho-app',
    authDomain: 'renrakucho-app.firebaseapp.com',
    storageBucket: 'renrakucho-app.firebasestorage.app',
    measurementId: 'G-2WKD1P4ZTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDP4oq3w9bYm_0ATm_soZfBPldjrE5t4',
    appId: '1:222477309527:android:3080712f4b95f3da1d3512',
    messagingSenderId: '222477309527',
    projectId: 'renrakucho-app',
    storageBucket: 'renrakucho-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzCUBE4G84pn2fR4ZQgLX7M7reG2Y4aA',
    appId: '1:222477309527:ios:de193360462979fc1d3512',
    messagingSenderId: '222477309527',
    projectId: 'renrakucho-app',
    storageBucket: 'renrakucho-app.firebasestorage.app',
    iosBundleId: 'com.example.renrakuchoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzCUBE4G84pn2fR4ZQgLX7M7reG2Y4aA',
    appId: '1:222477309527:ios:de193360462979fc1d3512',
    messagingSenderId: '222477309527',
    projectId: 'renrakucho-app',
    storageBucket: 'renrakucho-app.firebasestorage.app',
    iosBundleId: 'com.example.renrakuchoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD63D4XM6A-9_tqRW0YsBAh-XsLaEXGOIY',
    appId: '1:222477309527:web:abf733392d56017e1d3512',
    messagingSenderId: '222477309527',
    projectId: 'renrakucho-app',
    authDomain: 'renrakucho-app.firebaseapp.com',
    storageBucket: 'renrakucho-app.firebasestorage.app',
    measurementId: 'G-BMMMV5N0DN',
  );
}
